spring:
  application:
    name: panda-chatter-producer
  profiles:
    active: panda
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Panda Chatter Producer
    version: 1.0.0
